root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main src/main.go"
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  delay = 1000

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
